//! The v0 Tailwind-compatible utility synthesizer: utility classes in, CSS
//! text out — the "Tailwind build" stage of the Velqu pipeline
//! (utilities → CSS → profile check → renderer), with no node toolchain and
//! no network.
//!
//! v0 scope is exactly the renderer's M2c profile expressed as utilities:
//! display/flex/grid layout, spacing, sizing, the v3 color palette,
//! typography, borders/radius, and overflow. Everything else — variants
//! (`hover:`), arbitrary values (`w-[91px]`), fractional classes
//! (`w-1/2`), and utilities outside the renderer profile (`shadow`,
//! `opacity-50`, positioning) — produces a deterministic diagnostic,
//! never a silent drop.
//!
//! The output is plain CSS: one rule per class, in first-use order, so the
//! renderer's normal cascade applies (class specificity beats element
//! rules; stylesheets loaded after the generated sheet can still override
//! utilities at equal specificity).

use crate::palette;

/// One utility class the compiler could not map, with the reason. The
/// renderer never sees the class, so this list is the only place a dropped
/// utility is reported.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UtilityDiagnostic {
    /// The class as written in the markup.
    pub class: String,
    /// Why it was not compiled (and how to fix it, where known).
    pub message: String,
}

/// The result of compiling one document's utility classes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TailwindBuild {
    /// Generated CSS text (one rule per unique class, first-use order).
    pub css: String,
    /// Classes skipped, in first-use order (duplicates are not
    /// re-diagnosed).
    pub diagnostics: Vec<UtilityDiagnostic>,
    /// Number of utility rules in `css`.
    pub rules: usize,
}

/// Compiles Tailwind-compatible utility classes into CSS text.
///
/// ```
/// use velqu_tailwind::compile_utilities;
///
/// let build = compile_utilities(&["flex", "items-center", "gap-4"]);
/// assert!(build.diagnostics.is_empty());
/// assert!(build.css.contains(".flex { display: flex; }"));
/// assert!(build.css.contains("align-items: center"));
/// assert_eq!(build.rules, 3);
/// ```
pub fn compile_utilities(classes: &[&str]) -> TailwindBuild {
    // Preflight-lite: Tailwind sizing assumes border-box everywhere (the
    // universal selector has zero specificity, so any author rule wins).
    let mut css =
        String::from("/* generated by velqu-tailwind v0 */\n* { box-sizing: border-box; }\n");
    let mut diagnostics = Vec::new();
    let mut rules = 0usize;
    let mut seen: Vec<&str> = Vec::new();

    for class in classes {
        let class = class.trim();
        if class.is_empty() || seen.contains(&class) {
            continue;
        }
        seen.push(class);
        match utility_declarations(class) {
            Ok(declarations) => {
                let body = declarations
                    .iter()
                    .map(|(property, value)| format!("{property}: {value};"))
                    .collect::<Vec<_>>()
                    .join(" ");
                css.push_str(&format!(".{class} {{ {body} }}\n"));
                rules += 1;
            }
            Err(message) => diagnostics.push(UtilityDiagnostic {
                class: class.to_owned(),
                message,
            }),
        }
    }

    TailwindBuild {
        css,
        diagnostics,
        rules,
    }
}

/// Characters a class may contain for the v0 pipeline: CSS-escape-free
/// identifiers the renderer's selector parser handles as authored.
fn is_plain_class(class: &str) -> bool {
    class
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && class
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Maps one utility class to its declarations, or explains why it is
/// outside the v0 profile.
fn utility_declarations(class: &str) -> Result<Vec<(&'static str, String)>, String> {
    // Structural refusals first, with targeted guidance.
    if class.contains(':') {
        return Err(
            "variant classes (hover:, md:, dark:, …) are not applied in \
                    the v0 static profile"
                .into(),
        );
    }
    if class.contains('[') {
        return Err(
            "arbitrary values (e.g. w-[91px]) are deferred in profile v0; \
                    use the named scale"
                .into(),
        );
    }
    if class.contains('!') {
        return Err("the !important modifier is not part of profile v0".into());
    }
    if !is_plain_class(class) {
        return Err(format!(
            "class {class:?} needs CSS escaping (fractions, decimals, or \
             symbols); the v0 pipeline compiles plain [A-Za-z0-9-_] classes only"
        ));
    }

    // Three-level families: the first dash is part of the utility name, so
    // they are handled before the base/argument split.
    if let Some(rest) = class.strip_prefix("justify-items-") {
        return justify_items(rest);
    }
    if let Some(rest) = class.strip_prefix("justify-self-") {
        return justify_self(rest);
    }
    if let Some(rest) = class.strip_prefix("min-w-") {
        return Ok(vec![("min-width", size_value(rest)?)]);
    }
    if let Some(rest) = class.strip_prefix("min-h-") {
        return Ok(vec![("min-height", size_value(rest)?)]);
    }
    if let Some(rest) = class.strip_prefix("max-w-") {
        return Ok(vec![("max-width", max_width(rest)?)]);
    }
    if let Some(rest) = class.strip_prefix("max-h-") {
        return Ok(vec![("max-height", size_value(rest)?)]);
    }
    if let Some(rest) = class.strip_prefix("overflow-x-") {
        return overflow_axis("overflow-x", rest);
    }
    if let Some(rest) = class.strip_prefix("overflow-y-") {
        return overflow_axis("overflow-y", rest);
    }

    let (base, arg) = match class.split_once('-') {
        Some((base, arg)) => (base, Some(arg)),
        None => (class, None),
    };

    match (base, arg) {
        // -- display -----------------------------------------------------
        ("block", None) => Ok(vec![("display", "block".into())]),
        ("inline", None) => Ok(vec![("display", "inline".into())]),
        ("flex", None) => Ok(vec![("display", "flex".into())]),
        ("grid", None) => Ok(vec![("display", "grid".into())]),
        ("hidden", None) => Ok(vec![("display", "none".into())]),
        ("inline-block" | "inline-flex" | "inline-grid" | "table" | "contents", _) => {
            Err("display value outside the renderer profile (block/inline/flex/grid/none)".into())
        }

        // -- flex ------------------------------------------------------------
        ("flex", Some("row")) => Ok(vec![("flex-direction", "row".into())]),
        ("flex", Some("row-reverse")) => Ok(vec![("flex-direction", "row-reverse".into())]),
        ("flex", Some("col")) => Ok(vec![("flex-direction", "column".into())]),
        ("flex", Some("col-reverse")) => Ok(vec![("flex-direction", "column-reverse".into())]),
        ("flex", Some("wrap")) => Ok(vec![("flex-wrap", "wrap".into())]),
        ("flex", Some("wrap-reverse")) => {
            Err("flex-wrap: wrap-reverse is outside the renderer profile".into())
        }
        ("flex", Some("nowrap")) => Ok(vec![("flex-wrap", "nowrap".into())]),
        ("flex", Some("1")) => Ok(vec![
            ("flex-grow", "1".into()),
            ("flex-shrink", "1".into()),
            ("flex-basis", "0%".into()),
        ]),
        ("flex", Some("auto")) => Ok(vec![
            ("flex-grow", "1".into()),
            ("flex-shrink", "1".into()),
            ("flex-basis", "auto".into()),
        ]),
        ("flex", Some("none")) => Ok(vec![
            ("flex-grow", "0".into()),
            ("flex-shrink", "0".into()),
            ("flex-basis", "auto".into()),
        ]),
        ("flex", Some("initial")) => Ok(vec![
            ("flex-grow", "0".into()),
            ("flex-shrink", "1".into()),
            ("flex-basis", "auto".into()),
        ]),
        ("grow", None) => Ok(vec![("flex-grow", "1".into())]),
        ("grow", Some("0")) => Ok(vec![("flex-grow", "0".into())]),
        ("shrink", None) => Ok(vec![("flex-shrink", "1".into())]),
        ("shrink", Some("0")) => Ok(vec![("flex-shrink", "0".into())]),

        // -- alignment ----------------------------------------------------
        ("justify", Some("start" | "normal")) => Ok(vec![("justify-content", "flex-start".into())]),
        ("justify", Some("center")) => Ok(vec![("justify-content", "center".into())]),
        ("justify", Some("end")) => Ok(vec![("justify-content", "flex-end".into())]),
        ("justify", Some("between")) => Ok(vec![("justify-content", "space-between".into())]),
        ("justify", Some(other)) => Err(format!(
            "justify-{other} is outside the renderer profile \
             (start/center/end/between)"
        )),
        ("items", Some("start")) => Ok(vec![("align-items", "flex-start".into())]),
        ("items", Some("center")) => Ok(vec![("align-items", "center".into())]),
        ("items", Some("end")) => Ok(vec![("align-items", "flex-end".into())]),
        ("items", Some("stretch")) => Ok(vec![("align-items", "stretch".into())]),
        // Accepted; the renderer diagnoses the deferral and lays out as
        // flex-start — never silent.
        ("items", Some("baseline")) => Ok(vec![("align-items", "baseline".into())]),
        ("items", Some(other)) => Err(format!("unknown align-items value {other:?}")),
        ("self", Some("auto")) => Ok(vec![("align-self", "auto".into())]),
        ("self", Some("start")) => Ok(vec![("align-self", "flex-start".into())]),
        ("self", Some("center")) => Ok(vec![("align-self", "center".into())]),
        ("self", Some("end")) => Ok(vec![("align-self", "flex-end".into())]),
        ("self", Some("stretch")) => Ok(vec![("align-self", "stretch".into())]),
        ("self", Some(other)) => Err(format!("unknown align-self value {other:?}")),

        // -- grid ----------------------------------------------------------
        // Kept guard-free (no let-chains): the MSRV is 1.87.
        ("grid", Some(kind)) => grid_tracks(kind),
        ("col", Some(kind)) => grid_line("grid-column", kind),
        ("row", Some(kind)) => grid_line("grid-row", kind),

        // -- gap / spacing / sizing ---------------------------------------
        ("gap", Some(axis)) if axis.starts_with("x-") => {
            Ok(vec![("column-gap", spacing_px(&axis[2..], "gap-x")?)])
        }
        ("gap", Some(axis)) if axis.starts_with("y-") => {
            Ok(vec![("row-gap", spacing_px(&axis[2..], "gap-y")?)])
        }
        ("gap", Some(value)) => Ok(vec![("gap", spacing_px(value, "gap")?)]),
        ("p", Some(value)) => Ok(vec![("padding", spacing_px(value, "p")?)]),
        ("px", Some(value)) => Ok(vec![
            ("padding-left", spacing_px(value, "px")?),
            ("padding-right", spacing_px(value, "px")?),
        ]),
        ("py", Some(value)) => Ok(vec![
            ("padding-top", spacing_px(value, "py")?),
            ("padding-bottom", spacing_px(value, "py")?),
        ]),
        ("pt", Some(value)) => Ok(vec![("padding-top", spacing_px(value, "pt")?)]),
        ("pr", Some(value)) => Ok(vec![("padding-right", spacing_px(value, "pr")?)]),
        ("pb", Some(value)) => Ok(vec![("padding-bottom", spacing_px(value, "pb")?)]),
        ("pl", Some(value)) => Ok(vec![("padding-left", spacing_px(value, "pl")?)]),
        ("m", Some(value)) => Ok(vec![("margin", spacing_px(value, "m")?)]),
        ("mx", Some(value)) => Ok(vec![
            ("margin-left", spacing_px(value, "mx")?),
            ("margin-right", spacing_px(value, "mx")?),
        ]),
        ("my", Some(value)) => Ok(vec![
            ("margin-top", spacing_px(value, "my")?),
            ("margin-bottom", spacing_px(value, "my")?),
        ]),
        ("mt", Some(value)) => Ok(vec![("margin-top", spacing_px(value, "mt")?)]),
        ("mr", Some(value)) => Ok(vec![("margin-right", spacing_px(value, "mr")?)]),
        ("mb", Some(value)) => Ok(vec![("margin-bottom", spacing_px(value, "mb")?)]),
        ("ml", Some(value)) => Ok(vec![("margin-left", spacing_px(value, "ml")?)]),
        ("w", Some(value)) => Ok(vec![("width", size_value(value)?)]),
        ("h", Some(value)) => Ok(vec![("height", size_value(value)?)]),

        // -- typography ------------------------------------------------------
        ("text", Some("left" | "center" | "right")) => Ok(vec![(
            "text-align",
            class.rsplit('-').next().expect("non-empty").to_owned(),
        )]),
        ("text", Some(token)) => {
            if let Some((size, leading)) = is_font_size(token) {
                Ok(vec![
                    ("font-size", format!("{size}px")),
                    ("line-height", format!("{leading}px")),
                ])
            } else {
                match color_token(token) {
                    Some(hex) => Ok(vec![("color", hex.to_owned())]),
                    None => Err(format!("unknown text utility {class:?} (size or color?)")),
                }
            }
        }
        ("font", Some(weight)) => match font_weight(weight) {
            Some(value) => Ok(vec![("font-weight", value.to_owned())]),
            None => Err(format!(
                "unknown font utility {class:?} (font families are deferred)"
            )),
        },
        ("leading", Some("none")) => Ok(vec![("line-height", "1".into())]),
        ("leading", Some("tight")) => Ok(vec![("line-height", "1.25".into())]),
        ("leading", Some("snug")) => Ok(vec![("line-height", "1.375".into())]),
        ("leading", Some("normal")) => Ok(vec![("line-height", "1.5".into())]),
        ("leading", Some("relaxed")) => Ok(vec![("line-height", "1.625".into())]),
        ("leading", Some("loose")) => Ok(vec![("line-height", "2".into())]),
        ("tracking", _) => Err("letter-spacing is em-based and deferred in profile v0".into()),
        ("text-decoration", _) => Err("text decoration is outside profile v0".into()),

        // -- borders and radius ----------------------------------------------
        ("border", None) => Ok(default_border(1)),
        ("border", Some(token))
            if !token.is_empty() && token.chars().all(|c| c.is_ascii_digit()) =>
        {
            let width: u32 = token
                .parse()
                .map_err(|_| format!("invalid border width {token:?}"))?;
            Ok(default_border(width))
        }
        ("border", Some("solid")) => Ok(vec![("border-style", "solid".into())]),
        ("border", Some("none")) => Ok(vec![("border-style", "none".into())]),
        ("border", Some("dashed" | "dotted" | "double")) => {
            Err("border-style is outside the renderer profile (solid/none only)".into())
        }
        ("border", Some(color)) => match color_token(color) {
            Some(hex) => Ok(vec![("border-color", hex.to_owned())]),
            None => Err(format!("unknown border utility {class:?}")),
        },
        ("rounded", None) => Ok(vec![("border-radius", "4px".into())]),
        ("rounded", Some("none")) => Ok(vec![("border-radius", "0px".into())]),
        ("rounded", Some("sm")) => Ok(vec![("border-radius", "2px".into())]),
        ("rounded", Some("md")) => Ok(vec![("border-radius", "6px".into())]),
        ("rounded", Some("lg")) => Ok(vec![("border-radius", "8px".into())]),
        ("rounded", Some("xl")) => Ok(vec![("border-radius", "12px".into())]),
        ("rounded", Some("2xl")) => Ok(vec![("border-radius", "16px".into())]),
        ("rounded", Some("3xl")) => Ok(vec![("border-radius", "24px".into())]),
        ("rounded", Some("full")) => Ok(vec![("border-radius", "9999px".into())]),

        // -- overflow / white-space ------------------------------------------
        ("overflow", Some("visible" | "hidden" | "auto" | "scroll")) => Ok(vec![(
            "overflow",
            class.rsplit('-').next().expect("non-empty").to_owned(),
        )]),
        ("whitespace", Some("normal")) => Ok(vec![("white-space", "normal".into())]),
        ("whitespace", Some("nowrap")) => Ok(vec![("white-space", "nowrap".into())]),
        // The renderer collapses pre-line/pre-wrap to preserved-whitespace
        // layout (M2a profile); break-spaces is outside it entirely.
        ("whitespace", Some("pre" | "pre-line" | "pre-wrap")) => Ok(vec![(
            "white-space",
            class.rsplit('-').next().expect("non-empty").to_owned(),
        )]),
        ("whitespace", Some("break-spaces")) => {
            Err("white-space: break-spaces is outside the renderer profile".into())
        }

        // -- background ----------------------------------------------------------
        ("bg", Some(color)) => match color_token(color) {
            Some(hex) => Ok(vec![("background-color", hex.to_owned())]),
            None => Err(format!(
                "unknown bg utility {class:?} (gradients/images are deferred)"
            )),
        },

        // -- deliberately unsupported but common -----------------------------------
        ("absolute" | "fixed" | "sticky" | "static" | "relative", _)
        | ("inset", _)
        | ("top", _)
        | ("right", _)
        | ("bottom", _)
        | ("left", _) => {
            Err("positioning is outside the renderer profile v0 (layout is flow/flex/grid)".into())
        }
        ("shadow" | "opacity" | "cursor" | "z" | "transition" | "ring" | "blur", _)
        | (
            "container" | "truncate" | "underline" | "italic" | "uppercase" | "lowercase"
            | "capitalize" | "sr-only" | "antialiased",
            None,
        ) => Err(format!(
            "utility {class:?} is outside the renderer profile v0 \
             (shadows/opacity/cursor/z-index/transitions/decorations are deferred)"
        )),
        (
            "aspect" | "columns" | "list" | "object" | "align" | "select" | "appearance" | "order"
            | "basis" | "place" | "content" | "outline" | "accent" | "divide" | "space" | "scale"
            | "rotate" | "translate" | "skew" | "animate" | "fill" | "stroke",
            _,
        ) => Err(format!("utility family {base:?} is outside profile v0")),

        _ => Err(format!(
            "class {class:?} is not a known utility in profile v0 \
             (custom CSS still works through stylesheets)"
        )),
    }
}

/// `grid-cols-N`, `grid-rows-N`, and auto-flow classes.
fn grid_tracks(kind: &str) -> Result<Vec<(&'static str, String)>, String> {
    if let Some(count) = kind.strip_prefix("cols-") {
        let count = track_count(count)?;
        return Ok(vec![(
            "grid-template-columns",
            format!("repeat({count}, minmax(0, 1fr))"),
        )]);
    }
    if let Some(count) = kind.strip_prefix("rows-") {
        let count = track_count(count)?;
        return Ok(vec![(
            "grid-template-rows",
            format!("repeat({count}, minmax(0, 1fr))"),
        )]);
    }
    match kind {
        "flow-row" => Ok(vec![("grid-auto-flow", "row".into())]),
        "flow-col" => Ok(vec![("grid-auto-flow", "column".into())]),
        "flow-dense" | "flow-row-dense" | "flow-col-dense" => {
            Err("dense auto-placement is outside the renderer grid profile".into())
        }
        _ => Err(format!("unknown grid utility {kind:?}")),
    }
}

/// `col-span-N` / `col-start-N` / `col-end-N` and the row equivalents.
fn grid_line(property: &'static str, kind: &str) -> Result<Vec<(&'static str, String)>, String> {
    if let Some(count) = kind.strip_prefix("span-") {
        let count = track_count(count)?;
        return Ok(vec![(property, format!("span {count}"))]);
    }
    if let Some(line) = kind.strip_prefix("start-") {
        let line = track_count(line)?;
        return Ok(vec![(property, format!("{line} / auto"))]);
    }
    if let Some(line) = kind.strip_prefix("end-") {
        let line = track_count(line)?;
        return Ok(vec![(property, format!("auto / {line}"))]);
    }
    Err(format!("unknown {property} utility {kind:?}"))
}

/// `justify-items-<value>`: grid item alignment on the inline axis.
fn justify_items(value: &str) -> Result<Vec<(&'static str, String)>, String> {
    match value {
        "start" | "normal" => Ok(vec![("justify-items", "start".into())]),
        "center" => Ok(vec![("justify-items", "center".into())]),
        "end" => Ok(vec![("justify-items", "end".into())]),
        "stretch" => Ok(vec![("justify-items", "stretch".into())]),
        "baseline" => Ok(vec![("justify-items", "baseline".into())]),
        _ => Err(format!("unknown justify-items value {value:?}")),
    }
}

/// `justify-self-<value>`.
fn justify_self(value: &str) -> Result<Vec<(&'static str, String)>, String> {
    match value {
        "auto" => Ok(vec![("justify-self", "auto".into())]),
        "start" => Ok(vec![("justify-self", "start".into())]),
        "center" => Ok(vec![("justify-self", "center".into())]),
        "end" => Ok(vec![("justify-self", "end".into())]),
        "stretch" => Ok(vec![("justify-self", "stretch".into())]),
        "baseline" => Ok(vec![("justify-self", "baseline".into())]),
        _ => Err(format!("unknown justify-self value {value:?}")),
    }
}

/// `overflow-x-/overflow-y-<value>`.
fn overflow_axis(
    property: &'static str,
    value: &str,
) -> Result<Vec<(&'static str, String)>, String> {
    match value {
        "visible" | "hidden" | "auto" | "scroll" => Ok(vec![(property, value.to_owned())]),
        _ => Err(format!("unknown overflow value {value:?}")),
    }
}

/// The Tailwind `border` default: width, solid style, gray-200 color.
fn default_border(width: u32) -> Vec<(&'static str, String)> {
    vec![
        ("border-width", format!("{width}px")),
        ("border-style", "solid".into()),
        (
            "border-color",
            palette::lookup("gray-200")
                .expect("gray-200 exists")
                .to_owned(),
        ),
    ]
}

/// The Tailwind spacing scale: integer units are 4px per step (0.25rem);
/// `px` is 1px. Negative margins and fractional steps are v0-deferred.
fn spacing_px(token: &str, utility: &str) -> Result<String, String> {
    match token {
        "0" => Ok("0px".into()),
        "px" => Ok("1px".into()),
        "auto" => Err(format!(
            "margin: auto is deferred in profile v0 ({utility}-auto); center \
             with flex/grid containers"
        )),
        _ => {
            let units: f32 = token
                .parse()
                .map_err(|_| format!("unknown {utility} scale {token:?}"))?;
            if !(0.0..=96.0).contains(&units) || units.fract() != 0.0 {
                return Err(format!(
                    "{utility} scale {token:?} outside the v0 range (integer 0..=96)"
                ));
            }
            Ok(format!("{}px", units * 4.0))
        }
    }
}

/// `w`/`h`/`min-*`/`max-h` values: the spacing scale plus `full`/`auto`.
fn size_value(token: &str) -> Result<String, String> {
    match token {
        "full" => Ok("100%".into()),
        "auto" => Ok("auto".into()),
        "screen" => Err("viewport units (w-screen) are deferred in profile v0".into()),
        "fit" => Err("fit-content sizing is deferred in profile v0".into()),
        _ => spacing_px(token, "size"),
    }
}

/// Named `max-w-*` breakpoints (px, per Tailwind v3).
fn max_width(token: &str) -> Result<String, String> {
    let px = match token {
        "0" => return Ok("0px".into()),
        "none" => return Ok("none".into()),
        "full" => return Ok("100%".into()),
        "xs" => 320,
        "sm" => 384,
        "md" => 448,
        "lg" => 512,
        "xl" => 576,
        "2xl" => 672,
        "3xl" => 768,
        "4xl" => 896,
        "5xl" => 1024,
        "6xl" => 1152,
        "7xl" => 1280,
        _ => {
            return Err(format!(
                "unknown max-w scale {token:?} (prose/screens deferred)"
            ));
        }
    };
    Ok(format!("{px}px"))
}

/// `grid-cols-N` / `span N` counts (v0 caps at Tailwind's default grids).
fn track_count(token: &str) -> Result<u8, String> {
    let count: u8 = token
        .parse()
        .map_err(|_| format!("track count must be an integer, got {token:?}"))?;
    if count == 0 || count > 12 {
        return Err(format!("track count {count} outside the v0 range (1..=12)"));
    }
    Ok(count)
}

/// The `text-<size>` typography scale: (font-size px, line-height px).
fn is_font_size(token: &str) -> Option<(f32, f32)> {
    match token {
        "xs" => Some((12.0, 16.0)),
        "sm" => Some((14.0, 20.0)),
        "base" => Some((16.0, 24.0)),
        "lg" => Some((18.0, 28.0)),
        "xl" => Some((20.0, 28.0)),
        "2xl" => Some((24.0, 32.0)),
        "3xl" => Some((30.0, 36.0)),
        "4xl" => Some((36.0, 40.0)),
        "5xl" => Some((48.0, 48.0)),
        "6xl" => Some((60.0, 60.0)),
        "7xl" => Some((72.0, 72.0)),
        "8xl" => Some((96.0, 96.0)),
        "9xl" => Some((128.0, 128.0)),
        _ => None,
    }
}

/// `font-<weight>` names.
fn font_weight(token: &str) -> Option<&'static str> {
    match token {
        "thin" => Some("100"),
        "extralight" => Some("200"),
        "light" => Some("300"),
        "normal" => Some("400"),
        "medium" => Some("500"),
        "semibold" => Some("600"),
        "bold" => Some("700"),
        "extrabold" => Some("800"),
        "black" => Some("900"),
        _ => None,
    }
}

/// A color token: `white`/`black` or `<family>-<shade>` from the palette.
fn color_token(token: &str) -> Option<&'static str> {
    match token {
        "white" => Some("#ffffff"),
        "black" => Some("#000000"),
        other => palette::lookup(other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn layout_utilities_compile() {
        let build = compile_utilities(&["flex", "items-center", "justify-between", "gap-4"]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert_eq!(build.rules, 4);
        assert!(build.css.contains(".flex { display: flex; }"));
        assert!(build.css.contains("align-items: center"));
        assert!(build.css.contains("justify-content: space-between"));
        assert!(build.css.contains("gap: 16px"));
    }

    #[test]
    fn grid_utilities_compile() {
        let build = compile_utilities(&["grid", "grid-cols-3", "col-span-2", "row-start-1"]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert!(
            build
                .css
                .contains("grid-template-columns: repeat(3, minmax(0, 1fr))")
        );
        assert!(build.css.contains("grid-column: span 2"));
        assert!(build.css.contains("grid-row: 1 / auto"));
    }

    #[test]
    fn spacing_scale_is_four_px_per_unit() {
        let build = compile_utilities(&["p-4", "mt-0", "mx-px", "w-64", "h-full"]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert!(build.css.contains("padding: 16px"));
        assert!(build.css.contains("margin-top: 0px"));
        assert!(build.css.contains("margin-left: 1px"));
        assert!(build.css.contains("width: 256px"));
        assert!(build.css.contains("height: 100%"));
    }

    #[test]
    fn palette_colors_and_typography_compile() {
        let build = compile_utilities(&[
            "bg-rose-600",
            "text-white",
            "text-lg",
            "font-bold",
            "text-center",
            "border",
            "rounded-lg",
            "overflow-hidden",
        ]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert!(build.css.contains("background-color: #e11d48"));
        assert!(build.css.contains("color: #ffffff"));
        assert!(build.css.contains("font-size: 18px"));
        assert!(build.css.contains("line-height: 28px"));
        assert!(build.css.contains("font-weight: 700"));
        assert!(build.css.contains("text-align: center"));
        // `border` defaults to Tailwind's gray-200 solid 1px.
        assert!(build.css.contains("border-width: 1px"));
        assert!(build.css.contains("border-color: #e5e7eb"));
        assert!(build.css.contains("border-radius: 8px"));
        assert!(build.css.contains("overflow: hidden"));
    }

    #[test]
    fn deferred_structures_are_diagnosed_not_dropped_silently() {
        let build = compile_utilities(&[
            "hover:bg-red-500",
            "w-[91px]",
            "w-1/2",
            "p-2.5",
            "shadow-md",
            "absolute",
            "mx-auto",
            "underline",
            "unknown-class",
        ]);
        assert_eq!(build.rules, 0);
        assert_eq!(build.diagnostics.len(), 9, "{:?}", build.diagnostics);
        let messages: Vec<(&str, &str)> = build
            .diagnostics
            .iter()
            .map(|d| (d.class.as_str(), d.message.as_str()))
            .collect();
        let has = |class: &str, needle: &str| {
            messages
                .iter()
                .any(|(c, m)| *c == class && m.contains(needle))
        };
        assert!(has("hover:bg-red-500", "variant"));
        assert!(has("w-[91px]", "arbitrary"));
        assert!(has("w-1/2", "escaping"));
        assert!(has("p-2.5", "escaping"));
        assert!(has("shadow-md", "renderer profile"));
        assert!(has("absolute", "positioning"));
        assert!(has("mx-auto", "margin: auto"));
        assert!(has("underline", "renderer profile"));
        assert!(has("unknown-class", "not a known utility"));
    }

    #[test]
    fn duplicates_are_compiled_once_and_order_is_kept() {
        let build = compile_utilities(&["flex", "flex-col", "flex"]);
        assert_eq!(build.rules, 2);
        let flex_pos = build.css.find(".flex {").expect("flex rule");
        let col_pos = build.css.find(".flex-col {").expect("flex-col rule");
        assert!(flex_pos < col_pos, "first-use order");
    }

    #[test]
    fn later_utilities_can_override_earlier_ones_at_equal_specificity() {
        // `border border-red-500`: the later rule's border-color wins in the
        // cascade, matching Tailwind's expectation.
        let build = compile_utilities(&["border", "border-red-500"]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert_eq!(build.rules, 2);
        let border_pos = build.css.find(".border {").expect("border rule");
        let red_pos = build.css.find(".border-red-500 {").expect("color rule");
        assert!(border_pos < red_pos);
    }

    #[test]
    fn baseline_and_overflow_variants_still_map() {
        let build = compile_utilities(&[
            "items-baseline",
            "overflow-auto",
            "overflow-y-scroll",
            "justify-items-center",
            "self-stretch",
            "flex-1",
        ]);
        assert!(build.diagnostics.is_empty(), "{:?}", build.diagnostics);
        assert!(build.css.contains("align-items: baseline"));
        assert!(build.css.contains("overflow: auto"));
        assert!(build.css.contains("overflow-y: scroll"));
        assert!(build.css.contains("justify-items: center"));
        assert!(build.css.contains("align-self: stretch"));
        assert!(build.css.contains("flex-basis: 0%"));
    }
}
